version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u9n1t1t1
  build:
    commands:
      - docker build -t pos_nest -f ./dockerfile .
      - docker tag pos_nest:latest public.ecr.aws/u9n1t1t1/pos_nest:latest

  post_build:
    commands:
      - docker push public.ecr.aws/u9n1t1t1/pos_nest:latest
