version: "3.8"

services:
  app:
    env_file:
      - .env
    container_name: node_app_dev
    command: npm run start:debug
    networks:   # Use a custom network
      - devred
    ports:
      - 3000:3000
  postgres_service:
    container_name: postgres_dev
    env_file:
      - .env
    networks:   # Use a custom network
      - devred
    ports:
      - '5430:5432'
  pg_admin:
    container_name: pg_admin_dev
    env_file:
      - .env
    ports:
      - '5050:80'
    networks:   # Use a custom network
      - devred
  mysql:
    container_name: mysql_dev
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:   # Use a custom network
      - devred
  phpmyadmin:
    container_name: phpmyadmin_dev
    env_file:
      - .env
    ports:
      - '8080:80'
    networks:   # Use a custom network
      - devred
  sql-server:
    container_name: sql-server_dev
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1SuperPassword1
      - MSSQL_PID=Express
    ports:
      - '1433:1433'
    networks:   # Use a custom network
      - devred
networks:
  # Use a custom network
  devred:
    name: 'devred'
    driver: bridge


