version: "3.8"

services:
  app:
    env_file:
      - .env
    container_name: node_app_prod
    command: npm run start:prod
    networks:   # Use a custom network
      - prodred
    ports:
      - 3000:3000
  postgres_service:
    container_name: postgres_prod
    env_file:
      - .env
    networks:   # Use a custom network
      - prodred
    ports:
      - '5420:5432'
  pg_admin:
    container_name: pg_admin_prod
    env_file:
      - .env
    ports:
      - '5050:80'
    networks:   # Use a custom network
      - prodred
  mysql:
    container_name: mysql_prod
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:   # Use a custom network
      - prodred
  phpmyadmin:
    container_name: phpmyadmin_prod
    env_file:
      - .env
    ports:
      - '8080:80'
    networks:   # Use a custom network
      - prodred
  sql-server:
    container_name: sql-server_prod
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1SuperPassword1
      - MSSQL_PID=Express
    ports:
      - '1433:1433'
    networks:   # Use a custom network
      - prodred
networks:
  # Use a custom network
  prodred:
    name: 'prodred'
    driver: bridge


