version: '3.3'
services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    ports:
      - '5435:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/mydata
  pg_admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '5050:80'
volumes:
  postgres_data: {}

