version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    depends_on:
      - postgres_service
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
      - /usr/src/postgres_data
      - /usr/src/mysql_data
      - /usr/src/sqlserver_data
  postgres_service:
    image: postgres:14
    volumes:
      - ./postgres_data:/var/lib/postgresql/mydata
  pg_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres_service
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./sqlserver_data:/var/opt/mssql

