version: '3.3'
services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    ports:
      - '5435:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/mydata
  pg_admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '5050:80'
    depends_on:
      - postgres
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    ports:
      - '8080:80'
    depends_on:
      - mysql

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1SuperPassword1
      - MSSQL_PID=Express
    ports:
      - '1433:1433'
    volumes:
      - ./sqlserver_data:/var/opt/mssql
volumes:
  mysql_data: {}

